#ifndef CMAKESETTINGS_H_IN_
#define CMAKESETTINGS_H_IN_

#define RAYCHEL_VERSION "0.0.1"
#define RAYCHEL_VERSION_MAJOR "0"
#define RAYCHEL_VERSION_MINOR "0"
#define RAYCHEL_VERSION_PATCH "1"

#define RAYCHEL_VERSION_TAG RAYCHEL_VERSION "_" ""

#endif /* CMAKESETTINGS_H_IN_ */
